export const ro = {
  alerts: {
    success: "Email retrimis cu succes!",
    error: "A apărut o eroare. Vă rugăm să încercați din nou.",
    notAuthenticated: "Utilizatorul nu este autentificat.",
  },
  buttons: {
    back: "Înapoi",
    backToHome: "Înapoi la pagina principală",
    dashboard: "Panou de control",
    finalize: "Finalizează",
    goToHome: "Mergi la pagina principală",
    next: "Mai departe",
    register: "Înregistrează-te",
    resendEmail: "Retrimite email",
    sending: "Se trimite...",
    submit: "Trimite",
    submitting: "Se trimite...",
    saveChanges: "Salvează schimbările",
  },
  common: {
    loading: "Se încarcă...",
    refresh: "Reîmprospătează",
    noDataAvailable: "Nu există date disponibile",
    search: "Caută...",
    backToCalls: "Înapoi la apeluri",
  },
  chat: {
    disclaimer:
      "NextJourney poate afișa informații inexacte, inclusiv despre persoane, așa că verificați răspunsurile sale.",
    input: "Scrie un text",
    intro: "Cum te pot ajuta astăzi?",
    label: "Sunt încantat să te ajut!",
    send: "Trimite",
    welcome: "Bine ai venit",
  },
  call_page: {
    agent: "Agent",
    agents: "Agenți",
    agentDeadAir: "Agent Dead Air",
    agentTalkDuration: "Agent durată conversație",
    analytics: "Analitice",
    calls: "Apeluri",
    callDetails: "Detalii apel",
    callDetailsHeader: "Detalii apel",
    callDuration: "Durată conversație",
    callDurationDistribution: "Distribuția duratei apelurilor",
    callSummary: "Rezumat apel",
    chat: "Chat",
    client: "Client",
    clientTalkDuration: "Durată conversație client",
    close: "Închide",
    conversation: "Conversație",
    crosstalk: "Crosstalk",
    customer: "Client",
    date: "Data procesării",
    dayProcessed: "Data procesării",
    overview: "Prezentare generală",
    project: "Proiect",
    phoneNumber: "Număr de telefon",
    scorecards: "Fișe de evaluare",
    status: "Status",
    talkRatio: "Raport de conversație",
    totalDeadAir: "Total Dead Air",
    transactions: "Tranzacții",
    type: "Tip",
    wordFrequency: "Frecvența cuvintelor",
  },
  dashboard: {
    activeNow: "Activ Acum",
    amount: "Suma",
    approved: "Aprobat",
    averageTime: "Timp mediu de apel",
    conversations: "Conversații",
    customer: "Client",
    declined: "Respins",
    fromLastMonth: "față de luna trecută",
    processingTime: "Timp mediu de procesare",
    recentConversations: "Conversații recente",
    recentSales: "Vânzări recente",
    recentTransactions: "Tranzacții recente din magazinul tău.",
    refund: "Rambursare",
    sale: "Vânzare",
    sales: "Vânzări",
    score: "Scor mediu al apelurilor",
    sinceLastHour: "față de ultima oră",
    subscriptions: "Abonamente",
    totalCalls: "Total apeluri",
    transactions: "Tranzacții",
    type: "Tip",
    viewAll: "Vezi tot",
  },
  conversationsTab: {
    tableColumnName: "Nume",
    tableColumnPhone: "Număr de telefon",
    tableColumnScore: "Scor",
    tableColumnCallDuration: "Durată apel",
    tableColumnProject: "Proiect",
    tableColumnStatus: "Status",
    tableColumnActions: "Acțiuni",
    buttonDetails: "Vezi detaliile acestui apel",
    buttonDelete: "Șterge acest apel",
    statusLabels: {
      done: "Finalizat",
      processing: "În procesare",
      new: "Nou",
    },
    deleteConfirmTitle: "Confirmă Ștergerea",
    deleteConfirmDescription:
      "Sigur doriți să ștergeți acest apel? Această acțiune nu poate fi anulată.",
  },
  dateRangeSelector: {
    selectPeriodLabel: "Selectați o perioadă",
    periods: [
      "Ultimele 7 zile",
      "Ultimele 30 de zile",
      "Ultimele 90 de zile",
      "Personalizat",
    ],
    startDateLabel: "Data de început",
    endDateLabel: "Data de sfârșit",
    pickDate: "Alegeți o dată",
  },
  agentScoreChart: {
    title: "Scorul agentului în timp",
    description: "Tendința scorului mediu lunar",
    trendingUp: "În creștere",
    trendingDown: "În scădere",
    noChange: "Fără schimbare ",
    byPercentage: "cu {percentage}% luna aceasta",
    noDataAvailable: "Nu există date disponibile",
  },
  descriptions: {
    chatDisclaimer:
      "NextJourney poate afișa informații inexacte, inclusiv despre persoane, așa că verificați răspunsurile sale.",
    chooseDepartment:
      "Spune-ne în ce departament lucrezi. Vrem să știm unde faci diferența!",
    choosePartner:
      "Selectează partenerul cu care lucrezi pentru a începe cu dreptul!",
    chooseProject:
      "Selectează proiectul cu care ești asociat. Să trecem la treabă!",
    chooseTeamLeader: "Selectează coordonatorul echipei tale.",
    chooseProfileIcon: "Alege-ți un avatar pentru a-ți personaliza profilul.",
    default:
      "Completează pașii următori pentru a începe. Suntem încântați să te avem aici!",
    emailNotFound:
      "Nu s-a putut obține adresa de email. Vă rugăm să încercați din nou.",
    enterDob:
      "Introdu data nașterii tale. S-ar putea să te surprindem în ziua ta specială!",
    enterEmail:
      "Introduceți emailul și parola pentru a putea să te autentifici.",
    register: "Completează formularul de mai jos pentru a crea un cont nou.",
    success: "Ai finalizat cu succes configurarea.",
    totalCalls: "Totalul apelurilor în baza de date",
    totalCallsChange:
      "cu x% mai mult/mai puțin procesate comparativ cu luna trecută",
    verifyEmail:
      "Tocmai v-am trimis un email la <b>{email}</b>. Faceți clic pe linkul din email pentru a vă verifica adresa de email.",
    recentTransactions: "Tranzacții recente din magazinul tău.",
    welcome:
      "NextMind este platforma ta pentru colaborarea cu partenerii noștri. Să începem prin a completa câțiva pași pentru a personaliza experiența ta!",
  },
  dropdownMenu: {
    account: "Contul meu",
    logout: "Deconectare",
  },
  errors: {
    emailNotFound:
      "Adresa de email nu a fost găsită. Vă rugăm să vă înregistrați sau să încercați din nou.",
    enterDob: "Vă rugăm să introduceți data nașterii.",
    generalError: "A apărut o eroare. Vă rugăm să încercați din nou.",
    invalidCredential:
      "Date de autentificare invalide. Vă rugăm să verificați emailul și parola și să încercați din nou.",
    invalidEmail: "Adresa de email este formatată incorect.",
    invalidPassword: "Parola trebuie să aibă cel puțin 6 caractere.",
    selectDepartment: "Vă rugăm să selectați un departament.",
    selectPartner: "Vă rugăm să selectați un partener.",
    selectProject: "Vă rugăm să selectați un proiect.",
    selectTeamLeader: "Vă rugăm să selectați un coordonator de echipă.",
    userDisabled: "Acest utilizator a fost dezactivat.",
    wrongPassword: "Parolă incorectă. Vă rugăm să încercați din nou.",
  },
  gemini: {
    agentName: "Numele agentului este",
    agentText: "Agent:",
    assistant_instruction:
      "Ești un Quality Assurance, trebuie să fi prietenos, uman și empatic. Scopul tău este de a evalua apelurile din call center pentru a identifica punctele forte și domeniile care necesită îmbunătățiri, oferind feedback constructiv și sfaturi detaliate pentru a ajuta operatorii/agenții să își îmbunătățească tehnicile de vânzare, atitudinea generală și abordarea în timpul apelurilor. În plus, vei oferi orientări practice privind îmbunătățirea eficienței comunicării, gestionarea obiecțiilor clienților și crearea unei experiențe pozitive pentru aceștia, contribuind astfel la optimizarea performanței echipei și la atingerea obiectivelor organizaționale.",
    example_questions: {
      question1:
        "Cum ar trebui să abordez un client nemulțumit care dorește să închidă serviciul?",
      question2:
        "Ce tehnici pot folosi pentru a crește șansele de a încheia o vânzare?",
      question3:
        "Cum pot îmbunătăți tonul și atitudinea mea în timpul apelurilor?",
    },
    example_answers: {
      answer1:
        'Abordarea unui client nemulțumit care dorește să închidă serviciul necesită empatie, profesionalism și o dorință autentică de a-i înțelege frustrarea. Iată câțiva pași cheie:\n\n**1. Ascultă activ și validează:**\n\n* **Ascultă cu atenție** ce are de spus clientul, fără a-l întrerupe. Concentrează-te pe emoția din spatele cuvintelor, nu doar pe fapte. \n* **Confirmă** că ai înțeles situația și sentimentele clientului: "Înțeleg perfect de ce sunteți nemulțumit și vă asigur că voi face tot posibilul să clarific situația."\n* **Empatizează**: "Îmi imaginez cât de frustrant trebuie să fie să treceți prin asta."\n\n**2. Cere scuze și asumă-ți responsabilitatea:**\n\n* **Cere scuze sincer**, chiar dacă problema nu este direct vina ta. "Îmi pare foarte rău pentru experiența neplăcută pe care ați avut-o cu serviciul nostru."\n* **Asumă-ți responsabilitatea** pentru rezolvarea situației, fără a da vina pe alți colegi sau departamente.\n\n**3. Identifică problema și oferă soluții:**\n\n* **Pune întrebări specifice** pentru a înțelege exact de ce dorește clientul să închidă serviciul: "Ați putea să-mi dați mai multe detalii despre ce anume v-a nemulțumit?"\n* **Prezintă soluții concrete** și personalizate nevoilor clientului. De exemplu, oferă o perioadă de probă gratuită, o reducere la abonament, sau asistență tehnică dedicată. \n* **Fii realist** în privința a ceea ce poți oferi și nu promite lucruri pe care nu le poți îndeplini.\n\n**4. Menține o atitudine pozitivă și profesională:**\n\n* **Păstrează-ți calmul** și vorbește pe un ton calm și respectuos, chiar dacă clientul este furios sau agresiv verbal. \n* **Evită** să te justifici sau să te cerți cu clientul. \n* **Concentrează-te** pe găsirea unei soluții reciproc avantajoase.\n\n**5. Documentează interacțiunea:**\n\n* **Notează** toate detaliile importante ale conversației, inclusiv problemele semnalate de client și soluțiile propuse. \n* **Urmărește** implementarea soluției promise și asigură-te că clientul este mulțumit de rezultat.\n\n**Ține minte:**\n\n* Uneori, chiar dacă depui toate eforturile, este posibil ca unii clienți să decidă să închidă serviciul. Important este să gestionezi situația cu profesionalism și să lași clientului o impresie pozitivă, chiar și la plecare. \n* Folosește feedback-ul negativ ca pe o oportunitate de a învăța și de a îmbunătăți serviciile oferite.',
      answer2:
        'Iată câteva tehnici eficiente pentru a crește șansele de a încheia o vânzare în call center:\n\n**Înainte de apel:**\n\n* **Cercetează și califică lead-urile:** Asigură-te că persoanele pe care le contactezi fac parte din publicul țintă și au nevoie de produsul/serviciul tău. Folosește informații disponibile online (ex: LinkedIn, site-ul companiei) pentru a înțelege mai bine nevoile lor. \n* **Pregătește un "script" flexibil:** Un script te poate ghida în timpul conversației, însă evită să îl citești cuvânt cu cuvânt. Adaptează-l în funcție de reacțiile interlocutorului. \n* **Stabilește un obiectiv clar:** Ce vrei să obții din acest apel? O programare pentru o demonstrație? O cerere de ofertă? Având un obiectiv clar, te vei putea concentra mai bine pe parcursul conversației.\n\n**În timpul apelului:**\n\n* **Construiește o relație:** Fii empatic, prietenos și autentic. Arată interes față de interlocutor și nevoile sale.\n* **Ascultă activ:** Concentrează-te pe ceea ce spune interlocutorul și pune întrebări relevante pentru a demonstra că asculți.\n* **Evidențiază beneficiile, nu caracteristicile:** Nu te limita la a prezenta caracteristicile produsului/serviciului. Concentrează-te pe modul în care acestea pot rezolva problemele clientului sau îi pot îmbunătăți viața.\n* **Folosește povești și exemple concrete:** Oamenii rețin mai ușor informația prezentată sub formă de poveste. Folosește studii de caz și exemple pentru a demonstra valoarea produsului/serviciului.\n* **Gestionează obiecțiile:** Fii pregătit să răspunzi obiecțiilor cu calm și profesionalism. Transformă obiecțiile în oportunități de a oferi mai multe informații și de a demonstra valoarea produsului/serviciului.\n* **Încheie cu un "call to action" clar:** Nu lăsa conversația să se termine fără a propune o acțiune concretă, cum ar fi o programare a unei demonstrații sau trimiterea unei oferte personalizate.\n\n**După apel:**\n\n* **Urmărire promptă:** Contactează clientul în timp util, conform promisiunilor făcute în timpul apelului.\n* **Menține legătura:** Chiar dacă nu ai încheiat vânzarea imediat, menține legătura cu clientul prin email sau telefon. Oferă-i informații utile și demonstrează-i că ești interesat de succesul lui pe termen lung.\n\n**Recomandări suplimentare:**\n\n* **Perfecționează-ți tonul vocii:** Vorbește clar, cu entuziasm și încredere.\n* **Fii răbdător și perseverent:** Nu te descuraja dacă nu închei vânzarea la primul apel. Construirea unei relații de încredere necesită timp.\n* **Învață din fiecare interacțiune:** Analizează apelurile tale și identifică ce a funcționat și ce ar putea fi îmbunătățit.\n\nPrin aplicarea acestor tehnici și prin dedicare, vei putea crește semnificativ șansele de a încheia o vânzare în call center.',
      answer3:
        'Iată câteva sfaturi practice pentru a-ți îmbunătăți tonul și atitudinea în timpul apelurilor din call center:\n\n**Înainte de apel:**\n\n* **Pregătește-te mental:** Alocă-ți câteva minute înainte de apel pentru a te relaxa și a intra într-o stare de spirit pozitivă. \n* **Zâmbește:** Chiar dacă interlocutorul nu te poate vedea, zâmbetul se simte în voce și te va ajuta să pari mai prietenos și mai abordabil.\n* **Ajustează-ți postura:** Stai drept sau plimbă-te prin cameră în timp ce vorbești. O postură corectă te va ajuta să respiri mai ușor și să ai o voce mai puternică.\n\n**În timpul apelului:**\n\n* **Controlează-ți viteza de vorbire:** Vorbește clar, suficient de tare și într-un ritm moderat. Pauzele scurte între idei vor face mesajul tău mai ușor de urmărit.\n* **Modularea vocii:** Evită să vorbești monoton. Variază tonul vocii pentru a sublinia anumite cuvinte sau idei și pentru a menține interesul interlocutorului.\n* **Folosește un limbaj pozitiv:** Concentrează-te pe soluții, nu pe probleme. Înlocuiește frazele negative cu alternative pozitive: \n    * În loc de "Nu se poate", spune "Iată ce putem face..."\n    * În loc de "Nu știu", spune "Voi verifica și voi reveni cu un răspuns."\n* **Empatizează cu interlocutorul:** Arată că înțelegi perspectiva clientului și că îți pasă de problema sa.\n* **Fii răbdător și ascultă activ:** Acordă-i interlocutorului timpul necesar pentru a se exprima și ascultă cu atenție ce are de spus.\n* **Încheie cu o notă pozitivă:** Mulțumește interlocutorului pentru timpul acordat și exprimă-ți disponibilitatea de a-l ajuta și în viitor.\n\n**Exerciții practice:**\n\n* **Înregistrează-te:** Înregistrează-ți câteva apeluri și ascultă-le ulterior. Vei identifica mult mai ușor aspectele pe care le poți îmbunătăți.\n* **Joc de rol:** Exersează cu un coleg sau un prieten diverse scenarii de apel și oferă-ți feedback constructiv unul altuia.\n* **Tehnici de respirație și dicție:** Există numeroase resurse online cu exerciții de respirație și dicție care te pot ajuta să-ți îmbunătățești vocea și claritatea.\n\n**Amintește-ți:** Îmbunătățirea tonului și atitudinii necesită timp și efort conștient. Fii răbdător cu tine însuți și celebrează-ți progresele!',
    },
    feedback_headline: "De ce ați ales această evaluare? (opțional)",
    feedback_buttons: {
      correct: "Corect",
      easy: "Ușor",
      complete: "Complet",
      offensive: "Ofensator / Nesigur",
      incorrect: "Incorect",
      other: "Altul",
    },
    buttons: {
      submit: "Trimite",
    },
    feedback_note:
      "Chiar și atunci când Activitatea aplicațiilor Gemini este dezactivată, feedback-ul trimis va include și ultimele 24 de ore din conversațiile dvs. pentru a ajuta la îmbunătățirea Gemini.",
    frequentWords: "Cele mai frecvente cuvinte sunt:",
    generate_error: "Eroare la generarea răspunsului",
    learn_more: " Aflați mai multe",
    placeholders: {
      additionalFeedback: "Oferiți feedback suplimentar",
    },
    network_error: "Răspunsul de rețea nu a fost OK",
    occurrences: "ori",
    clientText: "Client:",
    projectName: "Proiectul agentului este",
    sentimentAverage: "Media de sentiment a conversației a fost de",
    sentimentScale: "pe o scală de la 1 la 5.",
    tooltip_copy: "Copiază",
    tooltip_copy_success: "Copiat!",
    tooltip_email: "Trimite pe email",
    tooltip_feedback_thumbs_down: "Răspuns negativ",
    tooltip_feedback_thumbs_up: "Răspuns pozitiv",
  },
  headers: {
    login: "Loghează-te în contul tău",
    dashboard: "Panou de control",
    register: "Înregistrează-te",
    close: "Închide",
    platform: "Platformă",
    nextMind: "NextMind",
    nextThing: "NextThing",
    light: "Luminos",
    dark: "Întunecat",
    system: "Sistem",
    settings: "Setări",
    theme: "Temă",
    language: "Limbă",
    languageSelect: {
      ro: "Română",
      en: "Engleză",
    },
  },
  homepage: {
    learnMore: "Află mai multe",
    start: "Începe acum",
    subtitle: "Platforma ta pentru colaborarea cu partenerii noștri.",
    title: "Bine ai venit la NextMind!",
  },
  labels: {
    dob: "Data Nașterii",
    department: "Departament",
    email: "Adresă de email",
    firstName: "Prenume",
    lastName: "Nume",
    partner: "Partener",
    password: "Parolă",
    profileIcon: "Avatar",
    project: "Proiect",
    teamLeader: "Coordonator de echipă",
    user: "Utilizator",
    company: "Companie",
  },
  links: {
    alreadyHaveAccount: "Deja ai un cont?",
    authentication: "Autentificare",
    discover: "Descoperă",
    dontHaveAccount: "Nu aveți un cont?",
    forgetPassword: "Ți-ai uitat parola?",
    license: "Licență",
    privacyPolicy: "Politica de Confidențialitate",
    register: "Înregistrați-vă",
    refundPolicy: "Politica de Returnare",
    support: "Suport",
    termsAndConditions: "Termeni și Condiții",
  },
  loading: {
    loadingAuthentication: "Se autentifică...",
    loadingIcons: "Se încarcă...",
    loadingPage: "Se încarcă...",
  },
  overviewTab: {
    title: "Prezentare generală",
    description: "Prezentare generală a activității firmei",
    handleConnectionError: "Nu s-a putut conecta la MongoDB: ",
    handleConnectionUnknownError: "A apărut o eroare necunoscută",
    handleInfoNotExist: "Nu există date pentru luna trecută",
    titlePresentation: "Apeluri lunare",
    titleRecentCalls: "Apeluri recente",
  },
  placeholders: {
    chatInput: "Scrie un text",
    department: "Alege un departament",
    dob: "Data Nașterii",
    partner: "Alege un partener",
    project: "Alege un proiect",
    teamLeader: "Alege un coordonator de echipă",
  },
  tabs: {
    conversations: "Conversații",
    overview: "Prezentare generală",
    sales: "Vânzări",
    transactions: "Tranzacții",
  },
  testimonials: [
    {
      author: "Sofia Davis",
      text: "Această bibliotecă mi-a economisit nenumărate ore de muncă și m-a ajutat să livrez designuri uimitoare clienților mei mai repede ca niciodată.",
    },
    {
      author: "John Smith",
      text: "Platforma aceasta este o adevărată comoară pentru orice designer. Mi-a schimbat complet modul de lucru.",
    },
    {
      author: "Maria Popescu",
      text: "Nu am întâlnit niciodată o resursă atât de completă și ușor de folosit. Recomand cu încredere.",
    },
    {
      author: "Alex Johnson",
      text: "Serviciile oferite de această bibliotecă sunt incomparabile. Am reușit să finalizez proiecte complexe în timp record.",
    },
  ],
  titles: {
    chooseDepartment: "Departamentul tău",
    choosePartner: "Alege partenerul",
    chooseProfileIcon: "Alege-ți un avatar",
    chooseProject: "Alege proiectul",
    chooseTeamLeader: "Coordonatorul echipei",
    default: "Bine ai venit!",
    enterDob: "Ziua ta specială",
    register: "Înregistrare",
    success: "Felicitări!",
    userProfile: "Editare Profil",
    verifyEmail: "Vă rugăm să vă verificați email-ul",
    welcome: "Bine ai venit la NextMind!",
  },
  userProfile: {
    avatarFallback: "Avatar utilizator",
    chooseDepartment: "Alegeți un departament",
    chooseProject: "Alegeți un proiect",
    company: "Companie",
    department: "Departament",
    description:
      "Faceți modificări în profilul dvs. aici. Apăsați Salvați când ați terminat.",
    editProfile: "Editare Profil",
    email: "Adresă de email",
    errors: {
      noUserData: "Nu sunt disponibile date despre utilizator",
      projectsError: "Eroare la încărcarea proiectelor",
      departmentsError: "Eroare la încărcarea departamentelor",
    },
    firstName: "Prenume",
    lastName: "Nume",
    loading: {
      loadingProjects: "Încărcare proiecte...",
      loadingDepartments: "Încărcare departamente...",
    },
    placeholders: {
      project: "Selectați un proiect",
      department: "Selectați un departament",
    },
    profileChangesSaved:
      "Modificările profilului dvs. au fost salvate cu succes.",
    saveChanges: "Salvați schimbările",
    title: "Editare Profil",
  },
  dialog: {
    title: "Modificări Salvate",
    description: "Modificările profilului dvs. au fost salvate cu succes.",
  },
  goTo: {
    title: "Alegeți unde doriți să mergeți",
    subtitle: "Selectați una dintre opțiunile de mai jos pentru a continua.",
  },
  callDurationDistribution: {
    title: "Durata apelurilor pentru Agent",
  },
  averageDurationDisplay: {
    title: "Durata medie a apelurilor",
  },
  averageScoreDisplay: {
    title: "Scor mediu",
  },
  averageSentimentDisplay: {
    title: "Sentiment mediu",
  },
  countDisplay: {
    title: "Numărul de apeluri",
  },
  monthlyBarChart: {
    title: "Numărul de apeluri pe lună",
  },
  agentsPage: {
    title: "Agenți",
    description: "Gestionează și vizualizează toți agenții",
    tableColumnName: "Nume",
    tableColumnUsername: "Nume utilizator",
    tableColumnProject: "Proiect",
    tableColumnActions: "Acțiuni",
    buttonDetails: "Vezi detaliile acestui agent",
    searchPlaceholder: "Caută agenți...",
    viewDetails: "Vezi detalii",
  },
  callsPage: {
    title: "Apeluri",
    description: "Vizualizează și gestionează înregistrările apelurilor",
    searchPlaceholder: "Caută apeluri...",
  },
  nextAiPage: {
    title: "Next AI",
    description: "Funcții și informații bazate pe inteligență artificială",
    // Add more specific translations for the Next AI page
  },
  agent_page: {
    id: "ID Agent",
    agentTitle: "Agent",
    agentDetails: "Detalii agent",
    agentInformation: "Informații agent",
    firstName: "Prenume",
    lastName: "Nume",
    username: "Nume utilizator",
    project: "Proiect",
    profile: "Profil",
    statistics: "Statistici",
    close: "Închide",
    projectOverview: "Prezentare generală a agentului",
    agentActivity: "Activitatea agentului",
    analytics: "Analitice",
    settings: "Setări",
    projectName: "Numele proiectului",
    recentCalls: "Apeluri recente",
    overview: {
      title: "Prezentare generală",
      description: "Prezentare generală a activității agentului",
    },
    activity: {
      title: "Activitate",
      description: "Activitatea agentului în ultimele 30 de zile",
    },
  },

  agentDetailsDrawer: {
    agentSummary: "Rezumatul Performanței Agentului",
    agentSummaryDescription: "Analiză generată de AI a performanței agentului",
  },
  callsTable: {
    phoneNumber: "Număr de telefon",
    date: "Data",
    duration: "Durata",
    score: "Scor",
    actions: "Acțiuni",
    view: "Vizualizare",
  },
  projectsPage: {
    title: "Proiecte",
    description: "Gestionează și vizualizează toate proiectele",
    searchPlaceholder: "Caută proiecte...",
    tableColumnName: "Nume proiect",
    tableColumnDescription: "Descriere",
    tableColumnAgentsCount: "Număr de Agenți",
    tableColumnActions: "Acțiuni",
    tableColumnCompanies: "Companii",
    tableColumnGreetings: "Greetings",
  },
  analyticsPage: {
    title: "Analize",
    description: "Vizualizează analize detaliate și rapoarte",
  },
  metadata: {
    dashboard: "Panou de control"
  },
};
